#!/usr/bin/env node
// Generated by CoffeeScript 1.6.2
(function() {
  var argv, fs, infatuate, input_filepath, model, text, text_length, _ref;

  infatuate = require('infatuate');

  argv = require('optimist').argv;

  text_length = (_ref = argv.size) != null ? _ref : 1000;

  input_filepath = argv.input;

  if (input_filepath == null) {
    console.log("Usage: ");
    console.log("   infatuate --input utf8_textfile --size <textlength>");
  } else {
    fs = require('fs');
    text = fs.readFileSync(input_filepath, {
      'encoding': 'utf-8'
    });
    model = infatuate.learn(text);
    console.log(model.draw_text(text_length));
  }

}).call(this);
